---
title: "Exercise_4"
author: "Baily"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

options(scipen = 1, digits = 2) #changes outputs to to decimal places.
knitr::opts_chunk$set(echo = TRUE)
packages_needed <- c("ggplot2", # graphics
                     "arm", # display() etc.
                     "ggfortify", # check model assumptions
                     "AICcmodavg", #average AIC models
                     "grid" #arrange objects
                     )
pk_to_install <- packages_needed [!( packages_needed %in% rownames(installed.packages())  )]
if(length(pk_to_install)>0 ){
  install.packages(pk_to_install,repos="http://cran.r-project.org")
}
#lapply(packages_needed, require, character.only = TRUE)
library(ggplot2)
library(arm)
library(ggfortify)
library(AICcmodavg)
library(grid)
```



```{r dataset}
frogs <- read.csv("frogs.csv")
```


```{r frogs}
ggplot(frogs, aes(altitude, pres.abs)) +
  geom_point(size=3) +
  geom_smooth(method="glm", method.args=list(family="binomial"(link="logit"))) +
  labs(title="GLM, binomial count (presence/absence)") +
  ylab ("Probability of Frog Presence") +
  xlab ("altitute")
```

```{r pmodel}
model_frogs<- glm(pres.abs ~ altitude, data = frogs, family=binomial())
model_frogs
```

```{r frog model 1}
coef(model_frogs)
confint(model_frogs)
summary(model_frogs)
```


